/* Generated by the Nim Compiler v0.19.1 */
/*   (c) 2018 Andreas Rumpf */

var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (typeof Int8Array === 'undefined') Int8Array = Array;
if (typeof Int16Array === 'undefined') Int16Array = Array;
if (typeof Int32Array === 'undefined') Int32Array = Array;
if (typeof Uint8Array === 'undefined') Uint8Array = Array;
if (typeof Uint16Array === 'undefined') Uint16Array = Array;
if (typeof Uint32Array === 'undefined') Uint32Array = Array;
if (typeof Float32Array === 'undefined') Float32Array = Array;
if (typeof Float64Array === 'undefined') Float64Array = Array;
var NTI146048 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI4062 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI148710 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI148725 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI148682 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI28057 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI148065 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI4050 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI148466 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI148430 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI148215 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI148604 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI148587 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI147900 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI147846 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI4058 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI37420 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI147803 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI147739 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI15746 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI4118 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI114 = {size: 0,kind: 40,base: null,node: null,finalizer: null};
var NTI138 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI4112 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI4026 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI4028 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI4042 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI4046 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI147704 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI147180 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI26395 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26391 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26387 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26383 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26379 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26375 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26371 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26367 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26363 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26359 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26355 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26351 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26347 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26343 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26339 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26335 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26331 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26327 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26323 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26319 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26204 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI26262 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI26260 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI26218 = {size: 0, kind: 14, base: null, node: null, finalizer: null};
var NTI26452 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI26450 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI26220 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI26448 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI26222 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI104 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI26248 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI26246 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI26499 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI26542 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI26254 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI26252 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI140 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI130 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI4008 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI26216 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI26214 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI26230 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI26228 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI147178 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI147177 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI148570 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NNI26216 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI26216.node = NNI26216;
var NNI4008 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI4008.node = NNI4008;
NTI26216.base = NTI4008;
NTI26214.base = NTI26216;
NTI26542.base = NTI26228;
var NNI26254 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "action", len: 0, typ: NTI140, name: "action", sons: null}, 
{kind: 1, offset: "encoding", len: 0, typ: NTI140, name: "encoding", sons: null}, 
{kind: 1, offset: "method", len: 0, typ: NTI140, name: "method", sons: null}, 
{kind: 1, offset: "target", len: 0, typ: NTI140, name: "target", sons: null}, 
{kind: 1, offset: "elements", len: 0, typ: NTI26542, name: "elements", sons: null}]};
NTI26254.node = NNI26254;
NTI26254.base = NTI26230;
NTI26252.base = NTI26254;
var NNI26248 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "defaultSelected", len: 0, typ: NTI130, name: "defaultSelected", sons: null}, 
{kind: 1, offset: "selected", len: 0, typ: NTI130, name: "selected", sons: null}, 
{kind: 1, offset: "selectedIndex", len: 0, typ: NTI104, name: "selectedIndex", sons: null}, 
{kind: 1, offset: "text", len: 0, typ: NTI140, name: "text", sons: null}, 
{kind: 1, offset: "value", len: 0, typ: NTI140, name: "value", sons: null}]};
NTI26248.node = NNI26248;
NTI26248.base = NTI26230;
NTI26246.base = NTI26248;
NTI26499.base = NTI26246;
var NNI26230 = {kind: 2, len: 11, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "classList", len: 0, typ: NTI26214, name: "classList", sons: null}, 
{kind: 1, offset: "checked", len: 0, typ: NTI130, name: "checked", sons: null}, 
{kind: 1, offset: "defaultChecked", len: 0, typ: NTI130, name: "defaultChecked", sons: null}, 
{kind: 1, offset: "defaultValue", len: 0, typ: NTI140, name: "defaultValue", sons: null}, 
{kind: 1, offset: "disabled", len: 0, typ: NTI130, name: "disabled", sons: null}, 
{kind: 1, offset: "form", len: 0, typ: NTI26252, name: "form", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI140, name: "name", sons: null}, 
{kind: 1, offset: "readOnly", len: 0, typ: NTI130, name: "readOnly", sons: null}, 
{kind: 1, offset: "options", len: 0, typ: NTI26499, name: "options", sons: null}, 
{kind: 1, offset: "clientWidth", len: 0, typ: NTI104, name: "clientWidth", sons: null}, 
{kind: 1, offset: "clientHeight", len: 0, typ: NTI104, name: "clientHeight", sons: null}]};
NTI26230.node = NNI26230;
NTI26220.base = NTI26222;
NTI26448.base = NTI26220;
NTI26450.base = NTI26220;
NTI26452.base = NTI26220;
var NNI26218 = {kind: 2, offset: 0, typ: null, name: null, len: 12, sons: {"1": {kind: 1, offset: 1, typ: NTI26218, name: "ElementNode", len: 0, sons: null}, 
"2": {kind: 1, offset: 2, typ: NTI26218, name: "AttributeNode", len: 0, sons: null}, 
"3": {kind: 1, offset: 3, typ: NTI26218, name: "TextNode", len: 0, sons: null}, 
"4": {kind: 1, offset: 4, typ: NTI26218, name: "CDATANode", len: 0, sons: null}, 
"5": {kind: 1, offset: 5, typ: NTI26218, name: "EntityRefNode", len: 0, sons: null}, 
"6": {kind: 1, offset: 6, typ: NTI26218, name: "EntityNode", len: 0, sons: null}, 
"7": {kind: 1, offset: 7, typ: NTI26218, name: "ProcessingInstructionNode", len: 0, sons: null}, 
"8": {kind: 1, offset: 8, typ: NTI26218, name: "CommentNode", len: 0, sons: null}, 
"9": {kind: 1, offset: 9, typ: NTI26218, name: "DocumentNode", len: 0, sons: null}, 
"10": {kind: 1, offset: 10, typ: NTI26218, name: "DocumentTypeNode", len: 0, sons: null}, 
"11": {kind: 1, offset: 11, typ: NTI26218, name: "DocumentFragmentNode", len: 0, sons: null}, 
"12": {kind: 1, offset: 12, typ: NTI26218, name: "NotationNode", len: 0, sons: null}}};
NTI26218.node = NNI26218;
var NNI26262 = {kind: 2, len: 91, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "background", len: 0, typ: NTI140, name: "background", sons: null}, 
{kind: 1, offset: "backgroundAttachment", len: 0, typ: NTI140, name: "backgroundAttachment", sons: null}, 
{kind: 1, offset: "backgroundColor", len: 0, typ: NTI140, name: "backgroundColor", sons: null}, 
{kind: 1, offset: "backgroundImage", len: 0, typ: NTI140, name: "backgroundImage", sons: null}, 
{kind: 1, offset: "backgroundPosition", len: 0, typ: NTI140, name: "backgroundPosition", sons: null}, 
{kind: 1, offset: "backgroundRepeat", len: 0, typ: NTI140, name: "backgroundRepeat", sons: null}, 
{kind: 1, offset: "border", len: 0, typ: NTI140, name: "border", sons: null}, 
{kind: 1, offset: "borderBottom", len: 0, typ: NTI140, name: "borderBottom", sons: null}, 
{kind: 1, offset: "borderBottomColor", len: 0, typ: NTI140, name: "borderBottomColor", sons: null}, 
{kind: 1, offset: "borderBottomStyle", len: 0, typ: NTI140, name: "borderBottomStyle", sons: null}, 
{kind: 1, offset: "borderBottomWidth", len: 0, typ: NTI140, name: "borderBottomWidth", sons: null}, 
{kind: 1, offset: "borderColor", len: 0, typ: NTI140, name: "borderColor", sons: null}, 
{kind: 1, offset: "borderLeft", len: 0, typ: NTI140, name: "borderLeft", sons: null}, 
{kind: 1, offset: "borderLeftColor", len: 0, typ: NTI140, name: "borderLeftColor", sons: null}, 
{kind: 1, offset: "borderLeftStyle", len: 0, typ: NTI140, name: "borderLeftStyle", sons: null}, 
{kind: 1, offset: "borderLeftWidth", len: 0, typ: NTI140, name: "borderLeftWidth", sons: null}, 
{kind: 1, offset: "borderRight", len: 0, typ: NTI140, name: "borderRight", sons: null}, 
{kind: 1, offset: "borderRightColor", len: 0, typ: NTI140, name: "borderRightColor", sons: null}, 
{kind: 1, offset: "borderRightStyle", len: 0, typ: NTI140, name: "borderRightStyle", sons: null}, 
{kind: 1, offset: "borderRightWidth", len: 0, typ: NTI140, name: "borderRightWidth", sons: null}, 
{kind: 1, offset: "borderStyle", len: 0, typ: NTI140, name: "borderStyle", sons: null}, 
{kind: 1, offset: "borderTop", len: 0, typ: NTI140, name: "borderTop", sons: null}, 
{kind: 1, offset: "borderTopColor", len: 0, typ: NTI140, name: "borderTopColor", sons: null}, 
{kind: 1, offset: "borderTopStyle", len: 0, typ: NTI140, name: "borderTopStyle", sons: null}, 
{kind: 1, offset: "borderTopWidth", len: 0, typ: NTI140, name: "borderTopWidth", sons: null}, 
{kind: 1, offset: "borderWidth", len: 0, typ: NTI140, name: "borderWidth", sons: null}, 
{kind: 1, offset: "bottom", len: 0, typ: NTI140, name: "bottom", sons: null}, 
{kind: 1, offset: "captionSide", len: 0, typ: NTI140, name: "captionSide", sons: null}, 
{kind: 1, offset: "clear", len: 0, typ: NTI140, name: "clear", sons: null}, 
{kind: 1, offset: "clip", len: 0, typ: NTI140, name: "clip", sons: null}, 
{kind: 1, offset: "color", len: 0, typ: NTI140, name: "color", sons: null}, 
{kind: 1, offset: "cursor", len: 0, typ: NTI140, name: "cursor", sons: null}, 
{kind: 1, offset: "direction", len: 0, typ: NTI140, name: "direction", sons: null}, 
{kind: 1, offset: "display", len: 0, typ: NTI140, name: "display", sons: null}, 
{kind: 1, offset: "emptyCells", len: 0, typ: NTI140, name: "emptyCells", sons: null}, 
{kind: 1, offset: "cssFloat", len: 0, typ: NTI140, name: "cssFloat", sons: null}, 
{kind: 1, offset: "font", len: 0, typ: NTI140, name: "font", sons: null}, 
{kind: 1, offset: "fontFamily", len: 0, typ: NTI140, name: "fontFamily", sons: null}, 
{kind: 1, offset: "fontSize", len: 0, typ: NTI140, name: "fontSize", sons: null}, 
{kind: 1, offset: "fontStretch", len: 0, typ: NTI140, name: "fontStretch", sons: null}, 
{kind: 1, offset: "fontStyle", len: 0, typ: NTI140, name: "fontStyle", sons: null}, 
{kind: 1, offset: "fontVariant", len: 0, typ: NTI140, name: "fontVariant", sons: null}, 
{kind: 1, offset: "fontWeight", len: 0, typ: NTI140, name: "fontWeight", sons: null}, 
{kind: 1, offset: "height", len: 0, typ: NTI140, name: "height", sons: null}, 
{kind: 1, offset: "left", len: 0, typ: NTI140, name: "left", sons: null}, 
{kind: 1, offset: "letterSpacing", len: 0, typ: NTI140, name: "letterSpacing", sons: null}, 
{kind: 1, offset: "lineHeight", len: 0, typ: NTI140, name: "lineHeight", sons: null}, 
{kind: 1, offset: "listStyle", len: 0, typ: NTI140, name: "listStyle", sons: null}, 
{kind: 1, offset: "listStyleImage", len: 0, typ: NTI140, name: "listStyleImage", sons: null}, 
{kind: 1, offset: "listStylePosition", len: 0, typ: NTI140, name: "listStylePosition", sons: null}, 
{kind: 1, offset: "listStyleType", len: 0, typ: NTI140, name: "listStyleType", sons: null}, 
{kind: 1, offset: "margin", len: 0, typ: NTI140, name: "margin", sons: null}, 
{kind: 1, offset: "marginBottom", len: 0, typ: NTI140, name: "marginBottom", sons: null}, 
{kind: 1, offset: "marginLeft", len: 0, typ: NTI140, name: "marginLeft", sons: null}, 
{kind: 1, offset: "marginRight", len: 0, typ: NTI140, name: "marginRight", sons: null}, 
{kind: 1, offset: "marginTop", len: 0, typ: NTI140, name: "marginTop", sons: null}, 
{kind: 1, offset: "maxHeight", len: 0, typ: NTI140, name: "maxHeight", sons: null}, 
{kind: 1, offset: "maxWidth", len: 0, typ: NTI140, name: "maxWidth", sons: null}, 
{kind: 1, offset: "minHeight", len: 0, typ: NTI140, name: "minHeight", sons: null}, 
{kind: 1, offset: "minWidth", len: 0, typ: NTI140, name: "minWidth", sons: null}, 
{kind: 1, offset: "overflow", len: 0, typ: NTI140, name: "overflow", sons: null}, 
{kind: 1, offset: "overflowX", len: 0, typ: NTI140, name: "overflowX", sons: null}, 
{kind: 1, offset: "overflowY", len: 0, typ: NTI140, name: "overflowY", sons: null}, 
{kind: 1, offset: "padding", len: 0, typ: NTI140, name: "padding", sons: null}, 
{kind: 1, offset: "paddingBottom", len: 0, typ: NTI140, name: "paddingBottom", sons: null}, 
{kind: 1, offset: "paddingLeft", len: 0, typ: NTI140, name: "paddingLeft", sons: null}, 
{kind: 1, offset: "paddingRight", len: 0, typ: NTI140, name: "paddingRight", sons: null}, 
{kind: 1, offset: "paddingTop", len: 0, typ: NTI140, name: "paddingTop", sons: null}, 
{kind: 1, offset: "pageBreakAfter", len: 0, typ: NTI140, name: "pageBreakAfter", sons: null}, 
{kind: 1, offset: "pageBreakBefore", len: 0, typ: NTI140, name: "pageBreakBefore", sons: null}, 
{kind: 1, offset: "position", len: 0, typ: NTI140, name: "position", sons: null}, 
{kind: 1, offset: "right", len: 0, typ: NTI140, name: "right", sons: null}, 
{kind: 1, offset: "scrollbar3dLightColor", len: 0, typ: NTI140, name: "scrollbar3dLightColor", sons: null}, 
{kind: 1, offset: "scrollbarArrowColor", len: 0, typ: NTI140, name: "scrollbarArrowColor", sons: null}, 
{kind: 1, offset: "scrollbarBaseColor", len: 0, typ: NTI140, name: "scrollbarBaseColor", sons: null}, 
{kind: 1, offset: "scrollbarDarkshadowColor", len: 0, typ: NTI140, name: "scrollbarDarkshadowColor", sons: null}, 
{kind: 1, offset: "scrollbarFaceColor", len: 0, typ: NTI140, name: "scrollbarFaceColor", sons: null}, 
{kind: 1, offset: "scrollbarHighlightColor", len: 0, typ: NTI140, name: "scrollbarHighlightColor", sons: null}, 
{kind: 1, offset: "scrollbarShadowColor", len: 0, typ: NTI140, name: "scrollbarShadowColor", sons: null}, 
{kind: 1, offset: "scrollbarTrackColor", len: 0, typ: NTI140, name: "scrollbarTrackColor", sons: null}, 
{kind: 1, offset: "tableLayout", len: 0, typ: NTI140, name: "tableLayout", sons: null}, 
{kind: 1, offset: "textAlign", len: 0, typ: NTI140, name: "textAlign", sons: null}, 
{kind: 1, offset: "textDecoration", len: 0, typ: NTI140, name: "textDecoration", sons: null}, 
{kind: 1, offset: "textIndent", len: 0, typ: NTI140, name: "textIndent", sons: null}, 
{kind: 1, offset: "textTransform", len: 0, typ: NTI140, name: "textTransform", sons: null}, 
{kind: 1, offset: "top", len: 0, typ: NTI140, name: "top", sons: null}, 
{kind: 1, offset: "verticalAlign", len: 0, typ: NTI140, name: "verticalAlign", sons: null}, 
{kind: 1, offset: "visibility", len: 0, typ: NTI140, name: "visibility", sons: null}, 
{kind: 1, offset: "width", len: 0, typ: NTI140, name: "width", sons: null}, 
{kind: 1, offset: "wordSpacing", len: 0, typ: NTI140, name: "wordSpacing", sons: null}, 
{kind: 1, offset: "zIndex", len: 0, typ: NTI104, name: "zIndex", sons: null}]};
NTI26262.node = NNI26262;
NTI26262.base = NTI4008;
NTI26260.base = NTI26262;
var NNI26222 = {kind: 2, len: 14, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "attributes", len: 0, typ: NTI26448, name: "attributes", sons: null}, 
{kind: 1, offset: "childNodes", len: 0, typ: NTI26450, name: "childNodes", sons: null}, 
{kind: 1, offset: "children", len: 0, typ: NTI26452, name: "children", sons: null}, 
{kind: 1, offset: "data", len: 0, typ: NTI140, name: "data", sons: null}, 
{kind: 1, offset: "firstChild", len: 0, typ: NTI26220, name: "firstChild", sons: null}, 
{kind: 1, offset: "lastChild", len: 0, typ: NTI26220, name: "lastChild", sons: null}, 
{kind: 1, offset: "nextSibling", len: 0, typ: NTI26220, name: "nextSibling", sons: null}, 
{kind: 1, offset: "nodeName", len: 0, typ: NTI140, name: "nodeName", sons: null}, 
{kind: 1, offset: "nodeType", len: 0, typ: NTI26218, name: "nodeType", sons: null}, 
{kind: 1, offset: "nodeValue", len: 0, typ: NTI140, name: "nodeValue", sons: null}, 
{kind: 1, offset: "parentNode", len: 0, typ: NTI26220, name: "parentNode", sons: null}, 
{kind: 1, offset: "previousSibling", len: 0, typ: NTI26220, name: "previousSibling", sons: null}, 
{kind: 1, offset: "innerHTML", len: 0, typ: NTI140, name: "innerHTML", sons: null}, 
{kind: 1, offset: "style", len: 0, typ: NTI26260, name: "style", sons: null}]};
NTI26222.node = NNI26222;
var NNI26204 = {kind: 2, len: 20, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "onabort", len: 0, typ: NTI26319, name: "onabort", sons: null}, 
{kind: 1, offset: "onblur", len: 0, typ: NTI26323, name: "onblur", sons: null}, 
{kind: 1, offset: "onchange", len: 0, typ: NTI26327, name: "onchange", sons: null}, 
{kind: 1, offset: "onclick", len: 0, typ: NTI26331, name: "onclick", sons: null}, 
{kind: 1, offset: "ondblclick", len: 0, typ: NTI26335, name: "ondblclick", sons: null}, 
{kind: 1, offset: "onerror", len: 0, typ: NTI26339, name: "onerror", sons: null}, 
{kind: 1, offset: "onfocus", len: 0, typ: NTI26343, name: "onfocus", sons: null}, 
{kind: 1, offset: "onkeydown", len: 0, typ: NTI26347, name: "onkeydown", sons: null}, 
{kind: 1, offset: "onkeypress", len: 0, typ: NTI26351, name: "onkeypress", sons: null}, 
{kind: 1, offset: "onkeyup", len: 0, typ: NTI26355, name: "onkeyup", sons: null}, 
{kind: 1, offset: "onload", len: 0, typ: NTI26359, name: "onload", sons: null}, 
{kind: 1, offset: "onmousedown", len: 0, typ: NTI26363, name: "onmousedown", sons: null}, 
{kind: 1, offset: "onmousemove", len: 0, typ: NTI26367, name: "onmousemove", sons: null}, 
{kind: 1, offset: "onmouseout", len: 0, typ: NTI26371, name: "onmouseout", sons: null}, 
{kind: 1, offset: "onmouseover", len: 0, typ: NTI26375, name: "onmouseover", sons: null}, 
{kind: 1, offset: "onmouseup", len: 0, typ: NTI26379, name: "onmouseup", sons: null}, 
{kind: 1, offset: "onreset", len: 0, typ: NTI26383, name: "onreset", sons: null}, 
{kind: 1, offset: "onselect", len: 0, typ: NTI26387, name: "onselect", sons: null}, 
{kind: 1, offset: "onsubmit", len: 0, typ: NTI26391, name: "onsubmit", sons: null}, 
{kind: 1, offset: "onunload", len: 0, typ: NTI26395, name: "onunload", sons: null}]};
NTI26204.node = NNI26204;
NTI26204.base = NTI4008;
NTI26222.base = NTI26204;
NTI26230.base = NTI26222;
NTI26228.base = NTI26230;
NTI147180.base = NTI147177;
var NNI147178 = {kind: 2, len: 4, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "heading", len: 0, typ: NTI26228, name: "heading", sons: null}, 
{kind: 1, offset: "kids", len: 0, typ: NTI147180, name: "kids", sons: null}, 
{kind: 1, offset: "sortId", len: 0, typ: NTI104, name: "sortId", sons: null}, 
{kind: 1, offset: "doSort", len: 0, typ: NTI130, name: "doSort", sons: null}]};
NTI147178.node = NNI147178;
NTI147177.base = NTI147178;
NTI148570.base = NTI147177;
NTI147704.base = NTI147177;
var NNI4046 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI4046.node = NNI4046;
var NNI4042 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI4042.node = NNI4042;
var NNI4028 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI4028.node = NNI4028;
NTI4112.base = NTI4026;
NTI4118.base = NTI4026;
var NNI4026 = {kind: 2, len: 6, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI4112, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI140, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI138, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI138, name: "trace", sons: null}, 
{kind: 1, offset: "raise_id", len: 0, typ: NTI114, name: "raise_id", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI4118, name: "up", sons: null}]};
NTI4026.node = NNI4026;
NTI4026.base = NTI4008;
NTI4028.base = NTI4026;
NTI4042.base = NTI4028;
NTI4046.base = NTI4042;
var NNI15746 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI140, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI104, name: "Field1", sons: null}]};
NTI15746.node = NNI15746;
NTI147739.base = NTI147177;
NTI147803.base = NTI104;
var NNI4058 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI4058.node = NNI4058;
NTI4058.base = NTI4028;
NTI147846.base = NTI147177;
NTI147900.base = NTI147177;
NTI148587.base = NTI26228;
NTI148604.base = NTI26228;
NTI148215.base = NTI147177;
NTI148430.base = NTI147177;
NTI148466.base = NTI147177;
var NNI4050 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI4050.node = NNI4050;
NTI4050.base = NTI4028;
NTI148065.base = NTI147177;
NTI28057.base = NTI26228;
NTI148682.base = NTI140;
var NNI148710 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI26228, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI104, name: "Field1", sons: null}]};
NTI148710.node = NNI148710;
NTI148725.base = NTI148710;
var NNI4062 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI4062.node = NNI4062;
NTI4062.base = NTI4028;
var NNI146048 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI104, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI130, name: "Field1", sons: null}]};
NTI146048.node = NNI146048;

function setConstr() {
		    var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

	
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_17630, src_17631, ti_17632) {
	var result_18055 = null;

		switch (ti_17632.kind) {
		case 21:
		case 22:
		case 23:
		case 5:
			if (!(is_fat_pointer_17601(ti_17632))) {
			result_18055 = src_17631;
			}
			else {
				result_18055 = [src_17631[0], src_17631[1]];
			}
			
			break;
		case 19:
			      if (dest_17630 === null || dest_17630 === undefined) {
        dest_17630 = {};
      }
      else {
        for (var key in dest_17630) { delete dest_17630[key]; }
      }
      for (var key in src_17631) { dest_17630[key] = src_17631[key]; }
      result_18055 = dest_17630;
    
			break;
		case 18:
		case 17:
			if (!((ti_17632.base == null))) {
			result_18055 = nimCopy(dest_17630, src_17631, ti_17632.base);
			}
			else {
			if ((ti_17632.kind == 17)) {
			result_18055 = (dest_17630 === null || dest_17630 === undefined) ? {m_type: ti_17632} : dest_17630;
			}
			else {
				result_18055 = (dest_17630 === null || dest_17630 === undefined) ? {} : dest_17630;
			}
			}
			nimCopyAux(result_18055, src_17631, ti_17632.node);
			break;
		case 24:
		case 4:
		case 27:
		case 16:
			      if (src_17631 === null) {
        result_18055 = null;
      }
      else {
        if (dest_17630 === null || dest_17630 === undefined) {
          dest_17630 = new Array(src_17631.length);
        }
        else {
          dest_17630.length = src_17631.length;
        }
        result_18055 = dest_17630;
        for (var i = 0; i < src_17631.length; ++i) {
          result_18055[i] = nimCopy(result_18055[i], src_17631[i], ti_17632.base);
        }
      }
    
			break;
		case 28:
			      if (src_17631 !== null) {
        result_18055 = src_17631.slice(0);
      }
    
			break;
		default: 
			result_18055 = src_17631;
			break;
		}

	return result_18055;

}

function makeNimstrLit(c_16625) {
		  var ln = c_16625.length;
  var result = new Array(ln);
  for (var i = 0; i < ln; ++i) {
    result[i] = c_16625.charCodeAt(i);
  }
  return result;
  

	
}

function arrayConstr(len_18116, value_18117, typ_18118) {
		    var result = new Array(len_18116);
    for (var i = 0; i < len_18116; ++i) result[i] = nimCopy(null, value_18117, typ_18118);
    return result;
  

	
}

function cstrToNimstr(c_16642) {
		  var ln = c_16642.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_16642.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_16642.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

	
}

function toJSStr(s_16659) {
		  var len = s_16659.length;
  var asciiPart = new Array(len);
  var fcc = String.fromCharCode;
  var nonAsciiPart = null;
  var nonAsciiOffset = 0;
  for (var i = 0; i < len; ++i) {
    if (nonAsciiPart !== null) {
      var offset = (i - nonAsciiOffset) * 2;
      var code = s_16659[i].toString(16);
      if (code.length == 1) {
        code = "0"+code;
      }
      nonAsciiPart[offset] = "%";
      nonAsciiPart[offset + 1] = code;
    }
    else if (s_16659[i] < 128)
      asciiPart[i] = fcc(s_16659[i]);
    else {
      asciiPart.length = i;
      nonAsciiOffset = i;
      nonAsciiPart = new Array((len - i) * 2);
      --i;
    }
  }
  asciiPart = asciiPart.join("");
  return (nonAsciiPart === null) ?
      asciiPart : asciiPart + decodeURIComponent(nonAsciiPart.join(""));
  

	
}

function raiseException(e_16218, ename_16219) {
		e_16218.name = ename_16219;
		if ((excHandler == 0)) {
		unhandledException(e_16218);
		}
		
		e_16218.trace = nimCopy(null, raw_write_stack_trace_16055(), NTI138);
		throw e_16218;

	
}

function addInt(a_17003, b_17004) {
		    var result = a_17003 + b_17004;
    if (result > 2147483647 || result < -2147483648) raiseOverflow();
    return result;
  

	
}

function chckIndx(i_18135, a_18136, b_18137) {
			var Tmp1;

	var result_18138 = 0;

	BeforeRet: do {
			if (!(a_18136 <= i_18135)) Tmp1 = false; else {				Tmp1 = (i_18135 <= b_18137);			}		if (Tmp1) {
		result_18138 = i_18135;
		break BeforeRet;
		}
		else {
		raiseIndexError();
		}
		
	} while (false);

	return result_18138;

}

function subInt(a_17021, b_17022) {
		    var result = a_17021 - b_17022;
    if (result > 2147483647 || result < -2147483648) raiseOverflow();
    return result;
  

	
}
var ConstSet2 = setConstr([65, 90]);

function chckRange(i_18154, a_18155, b_18156) {
			var Tmp1;

	var result_18157 = 0;

	BeforeRet: do {
			if (!(a_18155 <= i_18154)) Tmp1 = false; else {				Tmp1 = (i_18154 <= b_18156);			}		if (Tmp1) {
		result_18157 = i_18154;
		break BeforeRet;
		}
		else {
		raiseRangeError();
		}
		
	} while (false);

	return result_18157;

}
var ConstSet3 = setConstr(95, 32, 46);
var ConstSet4 = setConstr(95, 32, 46);

function mulInt(a_17039, b_17040) {
		    var result = a_17039 * b_17040;
    if (result > 2147483647 || result < -2147483648) raiseOverflow();
    return result;
  

	
}
var ConstSet5 = setConstr([97, 122]);
var ConstSet6 = setConstr([65, 90], [97, 122]);
var ConstSet7 = setConstr([97, 122]);
var ConstSet8 = setConstr([65, 90]);

function nimMax(a_17358, b_17359) {
		var Tmp1;

	var result_17360 = 0;

	BeforeRet: do {
		if ((b_17359 <= a_17358)) {
		Tmp1 = a_17358;
		}
		else {
		Tmp1 = b_17359;
		}
		
		result_17360 = Tmp1;
		break BeforeRet;
	} while (false);

	return result_17360;

}

function nimMin(a_17340, b_17341) {
		var Tmp1;

	var result_17342 = 0;

	BeforeRet: do {
		if ((a_17340 <= b_17341)) {
		Tmp1 = a_17340;
		}
		else {
		Tmp1 = b_17341;
		}
		
		result_17342 = Tmp1;
		break BeforeRet;
	} while (false);

	return result_17342;

}
var nimvm_7578 = false;
var nim_program_result = 0;
var global_raise_hook_13818 = [null];
var local_raise_hook_13823 = [null];
var out_of_mem_hook_13826 = [null];
  if (!Math.trunc) {
    Math.trunc = function(v) {
      v = +v;
      if (!isFinite(v)) return v;

      return (v - v % 1)   ||   (v < 0 ? -0 : v === 0 ? v : 0);
    };
  }
var dorender_28091 = [null];
var draw_timeout_28092 = [null];
var current_tree_28093 = [null];
var link_counter_28556 = [0];
var radio_counter_29052 = [0];
var alternative_148515 = [null];

function is_fat_pointer_17601(ti_17603) {
	var result_17604 = false;

	BeforeRet: do {
		result_17604 = !((ConstSet1[ti_17603.base.kind] != undefined));
		break BeforeRet;
	} while (false);

	return result_17604;

}

function nimCopyAux(dest_17635, src_17636, n_17638) {
		switch (n_17638.kind) {
		case 0:
			break;
		case 1:
			      dest_17635[n_17638.offset] = nimCopy(dest_17635[n_17638.offset], src_17636[n_17638.offset], n_17638.typ);
    
			break;
		case 2:
			L1: do {
				var i_18028 = 0;
				var colontmp__18030 = 0;
				colontmp__18030 = (n_17638.len - 1);
				var res_18033 = 0;
				L2: do {
						L3: while (true) {
						if (!(res_18033 <= colontmp__18030)) break L3;
							i_18028 = res_18033;
							nimCopyAux(dest_17635, src_17636, n_17638.sons[i_18028]);
							res_18033 += 1;
						}
				} while(false);
			} while(false);
			break;
		case 3:
			      dest_17635[n_17638.offset] = nimCopy(dest_17635[n_17638.offset], src_17636[n_17638.offset], n_17638.typ);
      for (var i = 0; i < n_17638.sons.length; ++i) {
        nimCopyAux(dest_17635, src_17636, n_17638.sons[i][1]);
      }
    
			break;
		}

	
}

function add_13838(x_13841, x_13841_Idx, y_13842) {
		      if (x_13841[x_13841_Idx] === null) { x_13841[x_13841_Idx] = []; }
      var off = x_13841[x_13841_Idx].length;
      x_13841[x_13841_Idx].length += y_13842.length;
      for (var i = 0; i < y_13842.length; ++i) {
        x_13841[x_13841_Idx][off+i] = y_13842.charCodeAt(i);
      }
    

	
}

function aux_write_stack_trace_15741(f_15743) {
					var Tmp3;

	var result_15744 = [null];

		var it_15752 = f_15743;
		var i_15754 = 0;
		var total_15756 = 0;
		var temp_frames_15763 = arrayConstr(64, {Field0: null, Field1: 0}, NTI15746);
		L1: do {
				L2: while (true) {
					if (!!((it_15752 == null))) Tmp3 = false; else {						Tmp3 = (i_15754 <= 63);					}				if (!Tmp3) break L2;
					temp_frames_15763[i_15754].Field0 = it_15752.procname;
					temp_frames_15763[i_15754].Field1 = it_15752.line;
					i_15754 += 1;
					total_15756 += 1;
					it_15752 = it_15752.prev;
				}
		} while(false);
		L4: do {
				L5: while (true) {
				if (!!((it_15752 == null))) break L5;
					total_15756 += 1;
					it_15752 = it_15752.prev;
				}
		} while(false);
		result_15744[0] = nimCopy(null, [], NTI138);
		if (!((total_15756 == i_15754))) {
		if (result_15744[0] != null) { result_15744[0] = (result_15744[0]).concat(makeNimstrLit("(")); } else { result_15744[0] = makeNimstrLit("("); };
		if (result_15744[0] != null) { result_15744[0] = (result_15744[0]).concat(cstrToNimstr(((total_15756 - i_15754))+"")); } else { result_15744[0] = cstrToNimstr(((total_15756 - i_15754))+"").slice(); };
		if (result_15744[0] != null) { result_15744[0] = (result_15744[0]).concat(makeNimstrLit(" calls omitted) ...\x0A")); } else { result_15744[0] = makeNimstrLit(" calls omitted) ...\x0A"); };
		}
		
		L6: do {
			var j_16028 = 0;
			var colontmp__16035 = 0;
			colontmp__16035 = (i_15754 - 1);
			var res_16038 = colontmp__16035;
			L7: do {
					L8: while (true) {
					if (!(0 <= res_16038)) break L8;
						j_16028 = res_16038;
						add_13838(result_15744, 0, temp_frames_15763[j_16028].Field0);
						if ((0 < temp_frames_15763[j_16028].Field1)) {
						if (result_15744[0] != null) { result_15744[0] = (result_15744[0]).concat(makeNimstrLit(", line: ")); } else { result_15744[0] = makeNimstrLit(", line: "); };
						if (result_15744[0] != null) { result_15744[0] = (result_15744[0]).concat(cstrToNimstr((temp_frames_15763[j_16028].Field1)+"")); } else { result_15744[0] = cstrToNimstr((temp_frames_15763[j_16028].Field1)+"").slice(); };
						}
						
						if (result_15744[0] != null) { result_15744[0] = (result_15744[0]).concat(makeNimstrLit("\x0A")); } else { result_15744[0] = makeNimstrLit("\x0A"); };
						res_16038 -= 1;
					}
			} while(false);
		} while(false);

	return result_15744[0];

}

function raw_write_stack_trace_16055() {
	var result_16057 = null;

		if (!((framePtr == null))) {
		result_16057 = nimCopy(null, (makeNimstrLit("Traceback (most recent call last)\x0A")).concat(aux_write_stack_trace_15741(framePtr)), NTI138);
		}
		else {
			result_16057 = nimCopy(null, makeNimstrLit("No stack traceback available\x0A"), NTI138);
		}
		

	return result_16057;

}

function unhandledException(e_16119) {
		var buf_16120 = [[]];
		if (!(((e_16119.message != null ? e_16119.message.length : 0) == 0))) {
		if (buf_16120[0] != null) { buf_16120[0] = (buf_16120[0]).concat(makeNimstrLit("Error: unhandled exception: ")); } else { buf_16120[0] = makeNimstrLit("Error: unhandled exception: "); };
		if (buf_16120[0] != null) { buf_16120[0] = (buf_16120[0]).concat(e_16119.message); } else { buf_16120[0] = e_16119.message.slice(); };
		}
		else {
		if (buf_16120[0] != null) { buf_16120[0] = (buf_16120[0]).concat(makeNimstrLit("Error: unhandled exception")); } else { buf_16120[0] = makeNimstrLit("Error: unhandled exception"); };
		}
		
		if (buf_16120[0] != null) { buf_16120[0] = (buf_16120[0]).concat(makeNimstrLit(" [")); } else { buf_16120[0] = makeNimstrLit(" ["); };
		add_13838(buf_16120, 0, e_16119.name);
		if (buf_16120[0] != null) { buf_16120[0] = (buf_16120[0]).concat(makeNimstrLit("]\x0A")); } else { buf_16120[0] = makeNimstrLit("]\x0A"); };
		if (buf_16120[0] != null) { buf_16120[0] = (buf_16120[0]).concat(raw_write_stack_trace_16055()); } else { buf_16120[0] = raw_write_stack_trace_16055().slice(); };
		var cbuf_16201 = toJSStr(buf_16120[0]);
		framePtr = null;
		  if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_16201);
  }
  else {
    throw cbuf_16201;
  }
  

	
}

function raiseOverflow() {
		var e_16465 = null;
		e_16465 = {m_type: NTI4046, parent: null, name: null, message: null, trace: null, raise_id: 0, up: null};
		e_16465.message = nimCopy(null, makeNimstrLit("over- or underflow"), NTI138);
		e_16465.parent = null;
		raiseException(e_16465, "OverflowError");

	
}

function is_whitespace_147652(text_147654) {
		     return !/[^\s]/.test(text_147654);
  

	
}

function is_whitespace_147669(x_147671) {
		var Tmp1;
		var Tmp2;

	var result_147672 = false;

	var F={procname:"dochack.isWhitespace",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 102;
		if (!(x_147671.nodeName == "#text")) Tmp2 = false; else {			Tmp2 = is_whitespace_147652(x_147671.textContent);		}		if (Tmp2) Tmp1 = true; else {			Tmp1 = (x_147671.nodeName == "#comment");		}		result_147672 = Tmp1;
	framePtr = F.prev;

	return result_147672;

}

function raiseIndexError() {
		var e_16555 = null;
		e_16555 = {m_type: NTI4058, parent: null, name: null, message: null, trace: null, raise_id: 0, up: null};
		e_16555.message = nimCopy(null, makeNimstrLit("index out of bounds"), NTI138);
		e_16555.parent = null;
		raiseException(e_16555, "IndexError");

	
}

function to_toc_147686(x_147688, father_147689) {
						var Tmp5;
						var Tmp6;
						var Tmp7;
			var Tmp15;

	var F={procname:"dochack.toToc",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		if ((x_147688.nodeName == "UL")) {
		F.line = 107;
		var f_147712 = {heading: null, kids: nimCopy(null, [], NTI147704), sortId: (father_147689.kids != null ? father_147689.kids.length : 0), doSort: false};
		F.line = 108;
		var i_147714 = 0;
		L1: do {
			F.line = 109;
				L2: while (true) {
				if (!(i_147714 < x_147688.childNodes.length)) break L2;
					F.line = 110;
					var nxt_147715 = addInt(i_147714, 1);
					L3: do {
						F.line = 111;
							L4: while (true) {
							if (!((nxt_147715 < x_147688.childNodes.length) && is_whitespace_147669(x_147688.childNodes[nxt_147715]))) break L4;
								F.line = 112;
								nxt_147715 = addInt(nxt_147715, 1);
							}
					} while(false);
						if (!(nxt_147715 < x_147688.childNodes.length)) Tmp7 = false; else {							Tmp7 = (x_147688.childNodes[i_147714].nodeName == "LI");						}						if (!Tmp7) Tmp6 = false; else {							Tmp6 = (x_147688.childNodes[i_147714].childNodes.length == 1);						}						if (!Tmp6) Tmp5 = false; else {							Tmp5 = (x_147688.childNodes[nxt_147715].nodeName == "UL");						}					if (Tmp5) {
					F.line = 115;
					var e_147747 = {heading: x_147688.childNodes[i_147714].childNodes[0], kids: nimCopy(null, [], NTI147739), sortId: (f_147712.kids != null ? f_147712.kids.length : 0), doSort: false};
					F.line = 116;
					var it_147748 = x_147688.childNodes[nxt_147715];
					L8: do {
						F.line = 117;
						var j_147758 = 0;
						F.line = 3636;
						var colontmp__147923 = 0;
						F.line = 117;
						colontmp__147923 = it_147748.childNodes.length;
						F.line = 3637;
						var i_147926 = 0;
						L9: do {
							F.line = 3638;
								L10: while (true) {
								if (!(i_147926 < colontmp__147923)) break L10;
									F.line = 3639;
									j_147758 = i_147926;
									F.line = 118;
									to_toc_147686(it_147748.childNodes[j_147758], e_147747);
									F.line = 3640;
									i_147926 = addInt(i_147926, 1);
								}
						} while(false);
					} while(false);
					F.line = 119;
					if (f_147712.kids != null) { f_147712.kids.push(e_147747); } else { f_147712.kids = [e_147747]; };
					F.line = 120;
					i_147714 = addInt(nxt_147715, 1);
					}
					else {
						F.line = 122;
						to_toc_147686(x_147688.childNodes[i_147714], f_147712);
						F.line = 123;
						i_147714 = addInt(i_147714, 1);
					}
					
				}
		} while(false);
		F.line = 124;
		if (father_147689.kids != null) { father_147689.kids.push(f_147712); } else { father_147689.kids = [f_147712]; };
		}
		else {
		if (is_whitespace_147669(x_147688)) {
		}
		else {
		if ((x_147688.nodeName == "LI")) {
		F.line = 128;
		var idx_147804 = nimCopy(null, [], NTI147803);
		L11: do {
			F.line = 129;
			var i_147814 = 0;
			F.line = 3636;
			var colontmp__147929 = 0;
			F.line = 129;
			colontmp__147929 = x_147688.childNodes.length;
			F.line = 3637;
			var i_147932 = 0;
			L12: do {
				F.line = 3638;
					L13: while (true) {
					if (!(i_147932 < colontmp__147929)) break L13;
						F.line = 3639;
						i_147814 = i_147932;
						if (!(is_whitespace_147669(x_147688.childNodes[i_147814]))) {
						F.line = 130;
						var Tmp14 = nimCopy(null, i_147814, NTI37420);
						if (idx_147804 != null) { idx_147804.push(Tmp14); } else { idx_147804 = [Tmp14]; };
						}
						
						F.line = 3640;
						i_147932 = addInt(i_147932, 1);
					}
			} while(false);
		} while(false);
			if (!((idx_147804 != null ? idx_147804.length : 0) == 2)) Tmp15 = false; else {				Tmp15 = (x_147688.childNodes[idx_147804[chckIndx(1, 0, idx_147804.length+0-1)-0]].nodeName == "UL");			}		if (Tmp15) {
		F.line = 132;
		var e_147854 = {heading: x_147688.childNodes[idx_147804[chckIndx(0, 0, idx_147804.length+0-1)-0]], kids: nimCopy(null, [], NTI147846), sortId: (father_147689.kids != null ? father_147689.kids.length : 0), doSort: false};
		F.line = 134;
		var it_147855 = x_147688.childNodes[idx_147804[chckIndx(1, 0, idx_147804.length+0-1)-0]];
		L16: do {
			F.line = 135;
			var j_147865 = 0;
			F.line = 3636;
			var colontmp__147936 = 0;
			F.line = 135;
			colontmp__147936 = it_147855.childNodes.length;
			F.line = 3637;
			var i_147939 = 0;
			L17: do {
				F.line = 3638;
					L18: while (true) {
					if (!(i_147939 < colontmp__147936)) break L18;
						F.line = 3639;
						j_147865 = i_147939;
						F.line = 136;
						to_toc_147686(it_147855.childNodes[j_147865], e_147854);
						F.line = 3640;
						i_147939 = addInt(i_147939, 1);
					}
			} while(false);
		} while(false);
		F.line = 137;
		if (father_147689.kids != null) { father_147689.kids.push(e_147854); } else { father_147689.kids = [e_147854]; };
		}
		else {
			L19: do {
				F.line = 139;
				var i_147885 = 0;
				F.line = 3636;
				var colontmp__147942 = 0;
				F.line = 139;
				colontmp__147942 = x_147688.childNodes.length;
				F.line = 3637;
				var i_147945 = 0;
				L20: do {
					F.line = 3638;
						L21: while (true) {
						if (!(i_147945 < colontmp__147942)) break L21;
							F.line = 3639;
							i_147885 = i_147945;
							F.line = 140;
							to_toc_147686(x_147688.childNodes[i_147885], father_147689);
							F.line = 3640;
							i_147945 = addInt(i_147945, 1);
						}
				} while(false);
			} while(false);
		}
		
		}
		else {
			F.line = 142;
		if (father_147689.kids != null) { father_147689.kids.push({heading: x_147688, kids: nimCopy(null, [], NTI147900), sortId: (father_147689.kids != null ? father_147689.kids.length : 0), doSort: false}); } else { father_147689.kids = [{heading: x_147688, kids: nimCopy(null, [], NTI147900), sortId: (father_147689.kids != null ? father_147689.kids.length : 0), doSort: false}]; };
		}
		}}
	framePtr = F.prev;

	
}

function extract_items_147192(x_147194, heading_147195, items_147198, items_147198_Idx) {
			var Tmp1;

	var F={procname:"dochack.extractItems",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		if ((x_147194 == null)) {
		F.line = 49;
		break BeforeRet;
		}
		
			if (!!((x_147194.heading == null))) Tmp1 = false; else {				Tmp1 = (x_147194.heading.textContent == heading_147195);			}		if (Tmp1) {
		L2: do {
			F.line = 51;
			var i_147237 = 0;
			F.line = 3636;
			var colontmp__147267 = 0;
			F.line = 51;
			colontmp__147267 = (x_147194.kids != null ? x_147194.kids.length : 0);
			F.line = 3637;
			var i_147270 = 0;
			L3: do {
				F.line = 3638;
					L4: while (true) {
					if (!(i_147270 < colontmp__147267)) break L4;
						F.line = 3639;
						i_147237 = i_147270;
						F.line = 52;
						if (items_147198[items_147198_Idx] != null) { items_147198[items_147198_Idx].push(x_147194.kids[chckIndx(i_147237, 0, x_147194.kids.length+0-1)-0].heading); } else { items_147198[items_147198_Idx] = [x_147194.kids[chckIndx(i_147237, 0, x_147194.kids.length+0-1)-0].heading]; };
						F.line = 3640;
						i_147270 = addInt(i_147270, 1);
					}
			} while(false);
		} while(false);
		}
		else {
			L5: do {
				F.line = 54;
				var i_147264 = 0;
				F.line = 3636;
				var colontmp__147273 = 0;
				F.line = 54;
				colontmp__147273 = (x_147194.kids != null ? x_147194.kids.length : 0);
				F.line = 3637;
				var i_147276 = 0;
				L6: do {
					F.line = 3638;
						L7: while (true) {
						if (!(i_147276 < colontmp__147273)) break L7;
							F.line = 3639;
							i_147264 = i_147276;
							F.line = 55;
							var it_147265 = x_147194.kids[chckIndx(i_147264, 0, x_147194.kids.length+0-1)-0];
							F.line = 56;
							extract_items_147192(it_147265, heading_147195, items_147198, items_147198_Idx);
							F.line = 3640;
							i_147276 = addInt(i_147276, 1);
						}
				} while(false);
			} while(false);
		}
		
	} while (false);
	framePtr = F.prev;

	
}

function tree_28351(tag_28353, kids_28355) {
	var result_28356 = null;

	var F={procname:"karax.tree",prev:framePtr,filename:"karax.nim",line:0};
	framePtr = F;
		F.line = 103;
		result_28356 = document.createElement(toJSStr(tag_28353));
		L1: do {
			F.line = 104;
			var k_28395 = null;
			F.line = 2265;
			var i_28399 = 0;
			L2: do {
				F.line = 2266;
					L3: while (true) {
					if (!(i_28399 < (kids_28355 != null ? kids_28355.length : 0))) break L3;
						F.line = 2267;
						k_28395 = kids_28355[chckIndx(i_28399, 0, kids_28355.length+0-1)-0];
						F.line = 105;
						result_28356.appendChild(k_28395);
						F.line = 2268;
						i_28399 = addInt(i_28399, 1);
					}
			} while(false);
		} while(false);
	framePtr = F.prev;

	return result_28356;

}

function text_28496(s_28498) {
	var result_28499 = null;

	var F={procname:"karax.text",prev:framePtr,filename:"karax.nim",line:0};
	framePtr = F;
		F.line = 113;
		result_28499 = document.createTextNode(s_28498);
	framePtr = F.prev;

	return result_28499;

}

function set_attr_29341(e_29343, key_29344, value_29345) {
	var F={procname:"karax.setAttr",prev:framePtr,filename:"karax.nim",line:0};
	framePtr = F;
		F.line = 273;
		e_29343.setAttribute(key_29344, value_29345);
	framePtr = F.prev;

	
}

function sys_fatal_20837(message_20843) {
	var F={procname:"sysFatal.sysFatal",prev:framePtr,filename:"../../lib/system.nim",line:0};
	framePtr = F;
		F.line = 2936;
		var e_20845 = null;
		F.line = 2937;
		e_20845 = {m_type: NTI4050, parent: null, name: null, message: null, trace: null, raise_id: 0, up: null};
		F.line = 2938;
		e_20845.message = nimCopy(null, message_20843, NTI138);
		F.line = 2939;
		raiseException(e_20845, "AssertionError");
	framePtr = F.prev;

	
}

function raise_assert_20832(msg_20834) {
	var F={procname:"system.raiseAssert",prev:framePtr,filename:"../../lib/system.nim",line:0};
	framePtr = F;
		F.line = 3892;
		sys_fatal_20837(msg_20834);
	framePtr = F.prev;

	
}

function failed_assert_impl_20881(msg_20883) {
	var F={procname:"system.failedAssertImpl",prev:framePtr,filename:"../../lib/system.nim",line:0};
	framePtr = F;
		F.line = 3899;
		raise_assert_20832(msg_20883);
	framePtr = F.prev;

	
}

function uncovered_148029(x_148031) {
			var Tmp1;
		var Tmp2;

	var result_148032 = null;

	var F={procname:"dochack.uncovered",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
	BeforeRet: do {
			if (!((x_148031.kids != null ? x_148031.kids.length : 0) == 0)) Tmp1 = false; else {				Tmp1 = !((x_148031.heading == null));			}		if (Tmp1) {
		F.line = 162;
		if (!(x_148031.heading.hasOwnProperty('__karaxMarker__'))) {
		Tmp2 = x_148031;
		}
		else {
		Tmp2 = null;
		}
		
		result_148032 = Tmp2;
		break BeforeRet;
		}
		
		F.line = 163;
		result_148032 = {heading: x_148031.heading, kids: nimCopy(null, [], NTI148065), sortId: x_148031.sortId, doSort: x_148031.doSort};
		L3: do {
			F.line = 165;
			var i_148082 = 0;
			F.line = 3636;
			var colontmp__148114 = 0;
			F.line = 165;
			colontmp__148114 = (x_148031.kids != null ? x_148031.kids.length : 0);
			F.line = 3637;
			var i_148117 = 0;
			L4: do {
				F.line = 3638;
					L5: while (true) {
					if (!(i_148117 < colontmp__148114)) break L5;
						F.line = 3639;
						i_148082 = i_148117;
						F.line = 166;
						var y_148083 = uncovered_148029(x_148031.kids[chckIndx(i_148082, 0, x_148031.kids.length+0-1)-0]);
						if (!((y_148083 == null))) {
						F.line = 167;
						if (result_148032.kids != null) { result_148032.kids.push(y_148083); } else { result_148032.kids = [y_148083]; };
						}
						
						F.line = 3640;
						i_148117 = addInt(i_148117, 1);
					}
			} while(false);
		} while(false);
		if (((result_148032.kids != null ? result_148032.kids.length : 0) == 0)) {
		F.line = 168;
		result_148032 = null;
		}
		
	} while (false);
	framePtr = F.prev;

	return result_148032;

}

function merge_tocs_148132(orig_148134, news_148135) {
	var result_148136 = null;

	var F={procname:"dochack.mergeTocs",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 171;
		result_148136 = uncovered_148029(orig_148134);
		if ((result_148136 == null)) {
		F.line = 173;
		result_148136 = news_148135;
		}
		else {
			L1: do {
				F.line = 175;
				var i_148164 = 0;
				F.line = 3636;
				var colontmp__148176 = 0;
				F.line = 175;
				colontmp__148176 = (news_148135.kids != null ? news_148135.kids.length : 0);
				F.line = 3637;
				var i_148179 = 0;
				L2: do {
					F.line = 3638;
						L3: while (true) {
						if (!(i_148179 < colontmp__148176)) break L3;
							F.line = 3639;
							i_148164 = i_148179;
							F.line = 176;
							if (result_148136.kids != null) { result_148136.kids.push(news_148135.kids[chckIndx(i_148164, 0, news_148135.kids.length+0-1)-0]); } else { result_148136.kids = [news_148135.kids[chckIndx(i_148164, 0, news_148135.kids.length+0-1)-0]]; };
							F.line = 3640;
							i_148179 = addInt(i_148179, 1);
						}
				} while(false);
			} while(false);
		}
		
	framePtr = F.prev;

	return result_148136;

}

function build_toc_148194(orig_148196, types_148198, procs_148199) {
	var result_148200 = null;

	var F={procname:"dochack.buildToc",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 179;
		var new_stuff_148216 = {heading: null, kids: nimCopy(null, [], NTI148215), doSort: true, sortId: 0};
		L1: do {
			F.line = 180;
			var t_148415 = null;
			F.line = 3933;
			var i_148499 = 0;
			F.line = 3934;
			var l_148501 = (types_148198 != null ? types_148198.length : 0);
			L2: do {
				F.line = 3935;
					L3: while (true) {
					if (!(i_148499 < l_148501)) break L3;
						F.line = 3936;
						t_148415 = types_148198[chckIndx(i_148499, 0, types_148198.length+0-1)-0];
						F.line = 181;
						var c_148431 = {heading: t_148415.cloneNode(true), kids: nimCopy(null, [], NTI148430), doSort: true, sortId: 0};
						F.line = 182;
						t_148415.__karaxMarker__ = true;
						L4: do {
							F.line = 183;
							var p_148440 = null;
							F.line = 3933;
							var i_148494 = 0;
							F.line = 3934;
							var l_148496 = (procs_148199 != null ? procs_148199.length : 0);
							L5: do {
								F.line = 3935;
									L6: while (true) {
									if (!(i_148494 < l_148496)) break L6;
										F.line = 3936;
										p_148440 = procs_148199[chckIndx(i_148494, 0, procs_148199.length+0-1)-0];
										if (!(p_148440.hasOwnProperty('__karaxMarker__'))) {
										F.line = 185;
										var xx_148441 = p_148440.parentNode.getElementsByClassName("attachedType");
										if ((((xx_148441 != null ? xx_148441.length : 0) == 1) && (xx_148441[chckIndx(0, 0, xx_148441.length+0-1)-0].textContent == t_148415.textContent))) {
										F.line = 188;
										var q_148451 = tree_28351(makeNimstrLit("A"), [text_28496(p_148440.title)]);
										F.line = 189;
										set_attr_29341(q_148451, "href", p_148440.getAttribute("href"));
										F.line = 190;
										if (c_148431.kids != null) { c_148431.kids.push({heading: q_148451, kids: nimCopy(null, [], NTI148466), sortId: 0, doSort: false}); } else { c_148431.kids = [{heading: q_148451, kids: nimCopy(null, [], NTI148466), sortId: 0, doSort: false}]; };
										F.line = 191;
										p_148440.__karaxMarker__ = true;
										}
										
										}
										
										F.line = 3937;
										i_148494 = addInt(i_148494, 1);
										if (!(((procs_148199 != null ? procs_148199.length : 0) == l_148496))) {
										F.line = 3938;
										failed_assert_impl_20881(makeNimstrLit("/Users/travis/build/nim-lang/Nim/lib/system.nim(3938, 11) `len(a) == L` seq modified while iterating over it"));
										}
										
									}
							} while(false);
						} while(false);
						F.line = 192;
						if (new_stuff_148216.kids != null) { new_stuff_148216.kids.push(c_148431); } else { new_stuff_148216.kids = [c_148431]; };
						F.line = 3937;
						i_148499 = addInt(i_148499, 1);
						if (!(((types_148198 != null ? types_148198.length : 0) == l_148501))) {
						F.line = 3938;
						failed_assert_impl_20881(makeNimstrLit("/Users/travis/build/nim-lang/Nim/lib/system.nim(3938, 11) `len(a) == L` seq modified while iterating over it"));
						}
						
					}
			} while(false);
		} while(false);
		F.line = 193;
		result_148200 = merge_tocs_148132(orig_148196, new_stuff_148216);
	framePtr = F.prev;

	return result_148200;

}

function add_28514(parent_28516, kid_28517) {
			var Tmp1;
				var Tmp2;

	var F={procname:"karax.add",prev:framePtr,filename:"karax.nim",line:0};
	framePtr = F;
			if (!(parent_28516.nodeName == "TR")) Tmp1 = false; else {				if ((kid_28517.nodeName == "TD")) Tmp2 = true; else {					Tmp2 = (kid_28517.nodeName == "TH");				}				Tmp1 = Tmp2;			}		if (Tmp1) {
		F.line = 117;
		var k_28518 = document.createElement("TD");
		F.line = 118;
		k_28518.appendChild(kid_28517);
		F.line = 119;
		parent_28516.appendChild(k_28518);
		}
		else {
			F.line = 121;
		parent_28516.appendChild(kid_28517);
		}
		
	framePtr = F.prev;

	
}

function set_class_29324(e_29326, value_29327) {
	var F={procname:"karax.setClass",prev:framePtr,filename:"karax.nim",line:0};
	framePtr = F;
		F.line = 270;
		e_29326.setAttribute("class", toJSStr(value_29327));
	framePtr = F.prev;

	
}

function to_html_147291(x_147293, is_root_147294) {
			var Tmp1;

		function HEX3Aanonymous_147345(a_147347, b_147348) {
					var Tmp1;

			var result_147349 = 0;

			var F={procname:"toHtml.:anonymous",prev:framePtr,filename:"dochack.nim",line:0};
			framePtr = F;
			BeforeRet: do {
					if (!!((a_147347.heading == null))) Tmp1 = false; else {						Tmp1 = !((b_147348.heading == null));					}				if (Tmp1) {
				F.line = 74;
				var x_147372 = a_147347.heading.textContent;
				F.line = 75;
				var y_147373 = b_147348.heading.textContent;
				if ((x_147372 < y_147373)) {
				F.line = 76;
				result_147349 = -1;
				break BeforeRet;
				}
				
				if ((y_147373 < x_147372)) {
				F.line = 77;
				result_147349 = 1;
				break BeforeRet;
				}
				
				F.line = 78;
				result_147349 = 0;
				break BeforeRet;
				}
				else {
					F.line = 81;
					result_147349 = subInt(a_147347.sortId, b_147348.sortId);
					break BeforeRet;
				}
				
			} while (false);
			framePtr = F.prev;

			return result_147349;

		}

	var result_147295 = null;

	var F={procname:"dochack.toHtml",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		if ((x_147293 == null)) {
		F.line = 59;
		result_147295 = null;
		break BeforeRet;
		}
		
		if (((x_147293.kids != null ? x_147293.kids.length : 0) == 0)) {
		if ((x_147293.heading == null)) {
		F.line = 61;
		result_147295 = null;
		break BeforeRet;
		}
		
		F.line = 62;
		result_147295 = x_147293.heading.cloneNode(true);
		break BeforeRet;
		}
		
		F.line = 63;
		result_147295 = tree_28351(makeNimstrLit("DIV"), []);
			if (!!((x_147293.heading == null))) Tmp1 = false; else {				Tmp1 = !(x_147293.heading.hasOwnProperty('__karaxMarker__'));			}		if (Tmp1) {
		F.line = 65;
		add_28514(result_147295, x_147293.heading.cloneNode(true));
		}
		
		F.line = 66;
		var ul_147342 = tree_28351(makeNimstrLit("UL"), []);
		if (is_root_147294) {
		F.line = 68;
		set_class_29324(ul_147342, makeNimstrLit("simple simple-toc"));
		}
		else {
			F.line = 70;
		set_class_29324(ul_147342, makeNimstrLit("simple"));
		}
		
		if (x_147293.doSort) {
		F.line = 72;
		x_147293.kids.sort(HEX3Aanonymous_147345);
		}
		
		L2: do {
			F.line = 83;
			var k_147615 = null;
			F.line = 3931;
			var colontmp__147633 = null;
			F.line = 83;
			colontmp__147633 = x_147293.kids;
			F.line = 3933;
			var i_147636 = 0;
			F.line = 3934;
			var l_147638 = (colontmp__147633 != null ? colontmp__147633.length : 0);
			L3: do {
				F.line = 3935;
					L4: while (true) {
					if (!(i_147636 < l_147638)) break L4;
						F.line = 3936;
						k_147615 = colontmp__147633[chckIndx(i_147636, 0, colontmp__147633.length+0-1)-0];
						F.line = 84;
						var y_147616 = to_html_147291(k_147615, false);
						if (!((y_147616 == null))) {
						F.line = 86;
						add_28514(ul_147342, tree_28351(makeNimstrLit("LI"), [y_147616]));
						}
						
						F.line = 3937;
						i_147636 = addInt(i_147636, 1);
						if (!(((colontmp__147633 != null ? colontmp__147633.length : 0) == l_147638))) {
						F.line = 3938;
						failed_assert_impl_20881(makeNimstrLit("/Users/travis/build/nim-lang/Nim/lib/system.nim(3938, 11) `len(a) == L` seq modified while iterating over it"));
						}
						
					}
			} while(false);
		} while(false);
		if (!((ul_147342.childNodes.length == 0))) {
		F.line = 87;
		add_28514(result_147295, ul_147342);
		}
		
		if ((result_147295.childNodes.length == 0)) {
		F.line = 88;
		result_147295 = null;
		}
		
	} while (false);
	framePtr = F.prev;

	return result_147295;

}

function replace_by_id_28162(id_28164, new_tree_28165) {
	var F={procname:"karax.replaceById",prev:framePtr,filename:"karax.nim",line:0};
	framePtr = F;
		F.line = 54;
		var x_28166 = document.getElementById(id_28164);
		F.line = 55;
		x_28166.parentNode.replaceChild(new_tree_28165, x_28166);
		F.line = 56;
		new_tree_28165.id = id_28164;
	framePtr = F.prev;

	
}

function togglevis_148529(d_148531) {
	var F={procname:"dochack.togglevis",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 198;
		    if (d_148531.style.display == 'none')
      d_148531.style.display = 'inline';
    else
      d_148531.style.display = 'none';
  
	framePtr = F.prev;

	
}

function groupBy(value_148547) {
	var F={procname:"dochack.groupBy",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 206;
		var toc_148548 = document.getElementById("toc-list");
		if ((alternative_148515[0] === null)) {
		F.line = 208;
		var tt_148571 = {heading: null, kids: nimCopy(null, [], NTI148570), sortId: 0, doSort: false};
		F.line = 209;
		to_toc_147686(toc_148548, tt_148571);
		F.line = 210;
		tt_148571 = tt_148571.kids[chckIndx(0, 0, tt_148571.kids.length+0-1)-0];
		F.line = 212;
		var types_148588 = [nimCopy(null, [], NTI148587)];
		F.line = 213;
		var procs_148605 = [nimCopy(null, [], NTI148604)];
		F.line = 215;
		extract_items_147192(tt_148571, "Types", types_148588, 0);
		F.line = 216;
		extract_items_147192(tt_148571, "Procs", procs_148605, 0);
		F.line = 217;
		extract_items_147192(tt_148571, "Converters", procs_148605, 0);
		F.line = 218;
		extract_items_147192(tt_148571, "Methods", procs_148605, 0);
		F.line = 219;
		extract_items_147192(tt_148571, "Templates", procs_148605, 0);
		F.line = 220;
		extract_items_147192(tt_148571, "Macros", procs_148605, 0);
		F.line = 221;
		extract_items_147192(tt_148571, "Iterators", procs_148605, 0);
		F.line = 223;
		var ntoc_148613 = build_toc_148194(tt_148571, types_148588[0], procs_148605[0]);
		F.line = 224;
		var x_148614 = to_html_147291(ntoc_148613, true);
		F.line = 225;
		alternative_148515[0] = tree_28351(makeNimstrLit("DIV"), [x_148614]);
		}
		
		if ((value_148547 == "type")) {
		F.line = 227;
		replace_by_id_28162("tocRoot", alternative_148515[0]);
		}
		else {
			F.line = 229;
		replace_by_id_28162("tocRoot", tree_28351(makeNimstrLit("DIV"), []));
		}
		
		F.line = 230;
		togglevis_148529(document.getElementById("toc-list"));
	framePtr = F.prev;

	
}
var db_148636 = [null];
var contents_148638 = [null];
var oldtoc_148869 = [null];
var timer_148870 = [null];

function raiseRangeError() {
		var e_16525 = null;
		e_16525 = {m_type: NTI4062, parent: null, name: null, message: null, trace: null, raise_id: 0, up: null};
		e_16525.message = nimCopy(null, makeNimstrLit("value out of range"), NTI138);
		e_16525.parent = null;
		raiseException(e_16525, "RangeError");

	
}

function nsuToLowerAsciiChar(c_128213) {
	var result_128214 = 0;

	var F={procname:"strutils.toLowerAscii",prev:framePtr,filename:"../../lib/pure/strutils.nim",line:0};
	framePtr = F;
		if ((ConstSet2[c_128213] != undefined)) {
		F.line = 218;
		result_128214 = chckRange(addInt(c_128213, 32), 0, 255);
		}
		else {
			F.line = 220;
			result_128214 = c_128213;
		}
		
	framePtr = F.prev;

	return result_128214;

}

function fuzzy_match_146044(pattern_146046, str_146047) {
							var Tmp4;
							var Tmp5;
								var Tmp6;

	var result_146051 = {Field0: 0, Field1: false};

	var F={procname:"fuzzysearch.fuzzyMatch",prev:framePtr,filename:"fuzzysearch.nim",line:0};
	framePtr = F;
		F.line = 37;
		var score_state_146052 = -100;
		F.line = 38;
		var header_matched_146053 = false;
		F.line = 39;
		var unmatched_leading_char_count_146055 = 0;
		F.line = 40;
		var consecutive_match_count_146057 = 0;
		F.line = 41;
		var str_index_146059 = 0;
		F.line = 42;
		var pat_index_146061 = 0;
		F.line = 43;
		var score_146063 = 0;
		L1: do {
			F.line = 49;
				L2: while (true) {
				if (!((str_index_146059 < (str_146047 != null ? str_146047.length : 0)) && (pat_index_146061 < (pattern_146046 != null ? pattern_146046.length : 0)))) break L2;
					L3: do {
						F.line = 51;
						var pattern_char_146070 = nsuToLowerAsciiChar(pattern_146046.charCodeAt(chckIndx(pat_index_146061, 0, pattern_146046.length+0-1)-0));
						F.line = 52;
						var str_char_146071 = nsuToLowerAsciiChar(str_146047.charCodeAt(chckIndx(str_index_146059, 0, str_146047.length+0-1)-0));
						if ((ConstSet3[pattern_char_146070] != undefined)) {
						F.line = 56;
						pat_index_146061 = addInt(pat_index_146061, 1);
						F.line = 57;
						break L3;
						}
						
						if ((ConstSet4[str_char_146071] != undefined)) {
						F.line = 59;
						str_index_146059 = addInt(str_index_146059, 1);
						F.line = 60;
						break L3;
						}
						
						if ((!(header_matched_146053) && (str_char_146071 == 58))) {
						F.line = 65;
						header_matched_146053 = true;
						F.line = 66;
						score_state_146052 = -100;
						F.line = 67;
						score_146063 = Math.trunc(Math.floor((5.0000000000000000e-01 * score_146063)));
						F.line = 68;
						pat_index_146061 = 0;
						F.line = 69;
						str_index_146059 = addInt(str_index_146059, 1);
						F.line = 70;
						break L3;
						}
						
						if ((str_char_146071 == pattern_char_146070)) {
						F.line = 73;
						switch (score_state_146052) {
						case -100:
						case 20:
							F.line = 75;
							score_state_146052 = 10;
							break;
						case 0:
							F.line = 78;
							score_state_146052 = 5;
							F.line = 78;
							score_146063 = addInt(score_146063, score_state_146052);
							break;
						case 10:
						case 5:
							F.line = 81;
							consecutive_match_count_146057 = addInt(consecutive_match_count_146057, 1);
							F.line = 82;
							score_state_146052 = 5;
							F.line = 83;
							score_146063 = addInt(score_146063, mulInt(5, consecutive_match_count_146057));
							if ((score_state_146052 == 10)) {
							F.line = 86;
							score_146063 = addInt(score_146063, 10);
							}
							
							F.line = 88;
							var on_boundary_146182 = (pat_index_146061 == (pattern_146046 != null ? (pattern_146046.length-1) : -1));
							if ((!(on_boundary_146182) && (str_index_146059 < (str_146047 != null ? (str_146047.length-1) : -1)))) {
							F.line = 91;
							var next_pattern_char_146183 = nsuToLowerAsciiChar(pattern_146046.charCodeAt(chckIndx(addInt(pat_index_146061, 1), 0, pattern_146046.length+0-1)-0));
							F.line = 92;
							var next_str_char_146184 = nsuToLowerAsciiChar(str_146047.charCodeAt(chckIndx(addInt(str_index_146059, 1), 0, str_146047.length+0-1)-0));
							F.line = 95;
							if (!!((ConstSet5[next_str_char_146184] != undefined))) Tmp4 = false; else {								Tmp4 = !((next_str_char_146184 == next_pattern_char_146183));							}							on_boundary_146182 = Tmp4;
							}
							
							if (on_boundary_146182) {
							F.line = 100;
							score_state_146052 = 20;
							F.line = 100;
							score_146063 = addInt(score_146063, score_state_146052);
							}
							
							break;
						case -1:
						case -3:
							F.line = 103;
							if (!((ConstSet6[str_146047.charCodeAt(chckIndx(subInt(str_index_146059, 1), 0, str_146047.length+0-1)-0)] != undefined))) Tmp5 = true; else {								if (!(ConstSet7[str_146047.charCodeAt(chckIndx(subInt(str_index_146059, 1), 0, str_146047.length+0-1)-0)] != undefined)) Tmp6 = false; else {									Tmp6 = (ConstSet8[str_146047.charCodeAt(chckIndx(str_index_146059, 0, str_146047.length+0-1)-0)] != undefined);								}								Tmp5 = Tmp6;							}							var is_leading_char_146239 = Tmp5;
							if (is_leading_char_146239) {
							F.line = 110;
							score_state_146052 = 10;
							}
							else {
								F.line = 114;
								score_state_146052 = 0;
								F.line = 114;
								score_146063 = addInt(score_146063, score_state_146052);
							}
							
							break;
						}
						F.line = 115;
						pat_index_146061 = addInt(pat_index_146061, 1);
						}
						else {
							F.line = 118;
							switch (score_state_146052) {
							case -100:
								F.line = 120;
								score_state_146052 = -3;
								F.line = 120;
								score_146063 = addInt(score_146063, score_state_146052);
								break;
							case 5:
								F.line = 123;
								score_state_146052 = -1;
								F.line = 123;
								score_146063 = addInt(score_146063, score_state_146052);
								F.line = 124;
								consecutive_match_count_146057 = 0;
								break;
							case -3:
								if ((unmatched_leading_char_count_146055 < 3)) {
								F.line = 128;
								score_state_146052 = -3;
								F.line = 128;
								score_146063 = addInt(score_146063, score_state_146052);
								}
								
								F.line = 129;
								unmatched_leading_char_count_146055 = addInt(unmatched_leading_char_count_146055, 1);
								break;
							default: 
								F.line = 132;
								score_state_146052 = -1;
								F.line = 132;
								score_146063 = addInt(score_146063, score_state_146052);
								break;
							}
						}
						
						F.line = 134;
						str_index_146059 = addInt(str_index_146059, 1);
					} while(false);
				}
		} while(false);
		F.line = 136;
		nimCopy(result_146051, {Field0: nimMax(0, score_146063), Field1: (0 < score_146063)}, NTI146048);
	framePtr = F.prev;

	return result_146051;

}

function text_28478(s_28480) {
	var result_28481 = null;

	var F={procname:"karax.text",prev:framePtr,filename:"karax.nim",line:0};
	framePtr = F;
		F.line = 112;
		result_28481 = document.createTextNode(toJSStr(s_28480));
	framePtr = F.prev;

	return result_28481;

}

function dosearch_148656(value_148658) {

		function HEX3Aanonymous_148760(a_148770, b_148772) {
			var result_148778 = 0;

			var F={procname:"dosearch.:anonymous",prev:framePtr,filename:"dochack.nim",line:0};
			framePtr = F;
				F.line = 274;
				result_148778 = subInt(b_148772["Field1"], a_148770["Field1"]);
			framePtr = F.prev;

			return result_148778;

		}

	var result_148659 = null;

	var F={procname:"dochack.dosearch",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		if (((db_148636[0] != null ? db_148636[0].length : 0) == 0)) {
		F.line = 240;
		var stuff_148667 = null;
		F.line = 241;
		    var request = new XMLHttpRequest();
    request.open("GET", "theindex.html", false);
    request.send(null);

    var doc = document.implementation.createHTMLDocument("theindex");
    doc.documentElement.innerHTML = request.responseText;

    //parser=new DOMParser();
    //doc=parser.parseFromString("<html></html>", "text/html");

    stuff_148667 = doc.documentElement;
    
		F.line = 254;
		db_148636[0] = nimCopy(null, stuff_148667.getElementsByClassName("reference"), NTI28057);
		F.line = 255;
		contents_148638[0] = nimCopy(null, [], NTI148682);
		L1: do {
			F.line = 256;
			var ahref_148691 = null;
			F.line = 3933;
			var i_148838 = 0;
			F.line = 3934;
			var l_148840 = (db_148636[0] != null ? db_148636[0].length : 0);
			L2: do {
				F.line = 3935;
					L3: while (true) {
					if (!(i_148838 < l_148840)) break L3;
						F.line = 3936;
						ahref_148691 = db_148636[0][chckIndx(i_148838, 0, db_148636[0].length+0-1)-0];
						F.line = 257;
						if (contents_148638[0] != null) { contents_148638[0].push(ahref_148691.getAttribute("data-doc-search-tag")); } else { contents_148638[0] = [ahref_148691.getAttribute("data-doc-search-tag")]; };
						F.line = 3937;
						i_148838 = addInt(i_148838, 1);
						if (!(((db_148636[0] != null ? db_148636[0].length : 0) == l_148840))) {
						F.line = 3938;
						failed_assert_impl_20881(makeNimstrLit("/Users/travis/build/nim-lang/Nim/lib/system.nim(3938, 11) `len(a) == L` seq modified while iterating over it"));
						}
						
					}
			} while(false);
		} while(false);
		}
		
		F.line = 258;
		var ul_148705 = tree_28351(makeNimstrLit("UL"), []);
		F.line = 259;
		result_148659 = tree_28351(makeNimstrLit("DIV"), []);
		F.line = 260;
		set_class_29324(result_148659, makeNimstrLit("search_results"));
		F.line = 261;
		var matches_148726 = nimCopy(null, [], NTI148725);
		L4: do {
			F.line = 262;
			var i_148743 = 0;
			F.line = 3636;
			var colontmp__148845 = 0;
			F.line = 262;
			colontmp__148845 = (db_148636[0] != null ? db_148636[0].length : 0);
			F.line = 3637;
			var i_148848 = 0;
			L5: do {
				F.line = 3638;
					L6: while (true) {
					if (!(i_148848 < colontmp__148845)) break L6;
						F.line = 3639;
						i_148743 = i_148848;
						L7: do {
							F.line = 263;
							var c_148744 = contents_148638[0][chckIndx(i_148743, 0, contents_148638[0].length+0-1)-0];
							if (((c_148744 == "Examples") || (c_148744 == "PEG construction"))) {
							F.line = 268;
							break L7;
							}
							
							F.line = 269;
							var colontmp__148943 = {Field0: 0, Field1: false};
							F.line = 269;
							var score_148745 = 0;
							F.line = 269;
							var matched_148746 = false;
							F.line = 269;
							nimCopy(colontmp__148943, fuzzy_match_146044(value_148658, c_148744), NTI146048);
							F.line = 269;
							score_148745 = colontmp__148943["Field0"];
							F.line = 269;
							matched_148746 = colontmp__148943["Field1"];
							if (matched_148746) {
							F.line = 271;
							if (matches_148726 != null) { matches_148726.push({Field0: db_148636[0][chckIndx(i_148743, 0, db_148636[0].length+0-1)-0], Field1: score_148745}); } else { matches_148726 = [{Field0: db_148636[0][chckIndx(i_148743, 0, db_148636[0].length+0-1)-0], Field1: score_148745}]; };
							}
							
						} while(false);
						F.line = 3640;
						i_148848 = addInt(i_148848, 1);
					}
			} while(false);
		} while(false);
		F.line = 273;
		matches_148726.sort(HEX3Aanonymous_148760);
		L8: do {
			F.line = 275;
			var i_148828 = 0;
			F.line = 3636;
			var colontmp__148851 = 0;
			F.line = 275;
			colontmp__148851 = nimMin((matches_148726 != null ? matches_148726.length : 0), 19);
			F.line = 3637;
			var i_148854 = 0;
			L9: do {
				F.line = 3638;
					L10: while (true) {
					if (!(i_148854 < colontmp__148851)) break L10;
						F.line = 3639;
						i_148828 = i_148854;
						F.line = 276;
						matches_148726[chckIndx(i_148828, 0, matches_148726.length+0-1)-0]["Field0"].innerHTML = matches_148726[chckIndx(i_148828, 0, matches_148726.length+0-1)-0]["Field0"].getAttribute("data-doc-search-tag");
						F.line = 277;
						add_28514(ul_148705, tree_28351(makeNimstrLit("LI"), [matches_148726[chckIndx(i_148828, 0, matches_148726.length+0-1)-0]["Field0"]]));
						F.line = 3640;
						i_148854 = addInt(i_148854, 1);
					}
			} while(false);
		} while(false);
		if ((ul_148705.childNodes.length == 0)) {
		F.line = 279;
		add_28514(result_148659, tree_28351(makeNimstrLit("B"), [text_28478(makeNimstrLit("no search results"))]));
		}
		else {
			F.line = 281;
			add_28514(result_148659, tree_28351(makeNimstrLit("B"), [text_28478(makeNimstrLit("search results"))]));
			F.line = 282;
			add_28514(result_148659, ul_148705);
		}
		
	framePtr = F.prev;

	return result_148659;

}

function search() {

		function wrapper_148886() {
			var F={procname:"search.wrapper",prev:framePtr,filename:"dochack.nim",line:0};
			framePtr = F;
				F.line = 289;
				var elem_148888 = document.getElementById("searchInput");
				F.line = 290;
				var value_148889 = elem_148888.value;
				if (!(((value_148889 != null ? value_148889.length : 0) == 0))) {
				if ((oldtoc_148869[0] === null)) {
				F.line = 293;
				oldtoc_148869[0] = document.getElementById("tocRoot");
				}
				
				F.line = 294;
				var results_148897 = dosearch_148656(value_148889);
				F.line = 295;
				replace_by_id_28162("tocRoot", results_148897);
				}
				else {
				if (!((oldtoc_148869[0] === null))) {
				F.line = 297;
				replace_by_id_28162("tocRoot", oldtoc_148869[0]);
				}
				}
			framePtr = F.prev;

			
		}

	var F={procname:"dochack.search",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		if (!((timer_148870[0] == null))) {
		F.line = 299;
		clearTimeout(timer_148870[0]);
		}
		
		F.line = 300;
		timer_148870[0] = setTimeout(wrapper_148886, 400);
	framePtr = F.prev;

	
}
